create table public.TAB_QUESTION (
	"COL_ID" INT,
	"COL_USER_ID" INT,
	"COL_RATING" INT,
	"COL_TITLE" TEXT,
	"COL_DESCRIPTION" TEXT,
	"COL_NUM_ANSWER" INT,
	"COL_CORRECT_ANSWER" INT,
	"COL_VIEWS" INT,
	"COL_CREATED" DATE,
	"COL_MODIFIED" DATE
);

insert into public.TAB_QUESTION ("COL_ID", "COL_USER_ID", "COL_RATING", "COL_TITLE", "COL_DESCRIPTION", "COL_NUM_ANSWER", "COL_CORRECT_ANSWER", "COL_VIEWS", "COL_CREATED", "COL_MODIFIED") values (1, 1, 84, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'Suspendisse potenti. In eleifend quam a odio.', 15, 1, 36, '2019-07-17 03:36:50', '2019-05-11 23:54:12');
insert into public.TAB_QUESTION ("COL_ID", "COL_USER_ID", "COL_RATING", "COL_TITLE", "COL_DESCRIPTION", "COL_NUM_ANSWER", "COL_CORRECT_ANSWER", "COL_VIEWS", "COL_CREATED", "COL_MODIFIED") values (2, 2, 65, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 24, 2, 4, '2019-05-20 07:48:40', '2020-01-20 09:45:06');
insert into public.TAB_QUESTION ("COL_ID", "COL_USER_ID", "COL_RATING", "COL_TITLE", "COL_DESCRIPTION", "COL_NUM_ANSWER", "COL_CORRECT_ANSWER", "COL_VIEWS", "COL_CREATED", "COL_MODIFIED") values (3, 3, 58, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 95, 3, 5, '2020-01-24 13:10:44', '2019-11-05 13:05:42');
insert into public.TAB_QUESTION ("COL_ID", "COL_USER_ID", "COL_RATING", "COL_TITLE", "COL_DESCRIPTION", "COL_NUM_ANSWER", "COL_CORRECT_ANSWER", "COL_VIEWS", "COL_CREATED", "COL_MODIFIED") values (4, 4, 16, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Nulla ut erat id mauris vulputate elementum.', 93, 4, 24, '2019-05-16 05:57:55', '2020-01-11 13:25:04');
insert into public.TAB_QUESTION ("COL_ID", "COL_USER_ID", "COL_RATING", "COL_TITLE", "COL_DESCRIPTION", "COL_NUM_ANSWER", "COL_CORRECT_ANSWER", "COL_VIEWS", "COL_CREATED", "COL_MODIFIED") values (5, 5, 56, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 20, 5, 29, '2019-11-29 09:11:50', '2020-02-14 20:15:59');
